config/routes.rb
Rails.application.routes.draw do
  resources :projects
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :moderator, :admin]
  after_initialize :set_defaulet_role, :if => :new_record?
  def set_defaulet_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.all
   @project = Project.new

  end

 # GET /projects/new
 def new
   @project = Project.new
 end

 # GET /projects/1/edit
 def edit
 end

 # POST /projects or /projects.json
 def create
   @project = Project.new(project_params)

   respond_to do |format|
     if @project.save
       format.html { redirect_to root_path, notice: "Project was successfully created." }
       format.json { render :show, status: :created, location: @project }
     else
       format.html { render :new, status: :unprocessable_entity }
       format.json { render json: @project.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /projects/1 or /projects/1.json
 def update
   respond_to do |format|
     if @project.update(project_params)
       format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
       format.json { render :show, status: :ok, location: @project }
     else
       format.html { render :edit, status: :unprocessable_entity }
       format.json { render json: @project.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /projects/1 or /projects/1.json
 def destroy
   @project.destroy

   respond_to do |format|
     format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_project
     @project = Project.find(params[:id])
   end

   # Only allow a list of trusted parameters through.
   def project_params
     params.require(:project).permit(:name, :description, :user_id)
   end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
    if @project.user != current_user
      redirect_to root_path
    end
    
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_path, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to current_user.email, root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
       <ul class="navbar-nav">
        <li class="nav-item">
        <%- if controller_name == 'pages' %>
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-right: 10px;">New Project</button>

<% end %>

        </li>
 <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= current_user.email %>
          </a>

          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><%= link_to "Edit Account", edit_user_registration_path, class:"dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Logout', destroy_user_session_path, 'data-turbo-method': :delete, class: "dropdown-item" %></li>
          </ul>
        </li>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Basecamp1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' if current_user %>
    <div class="container" style="margin-top: 15px;">
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/_new.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= stylesheet_link_tag "glavniy" %>

<body class="body-1">



  <div class="container">
    <% if current_user %>

  <h1 class="h1-project">Projects</h1> <br /><br />
          <div class="row">
      <% @projects.each do |project| %>
          <% if current_user.id == project.user.id %>


  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= project.name %></h5>
      <p class="card-text"><%= project.description %></p>
      <%= link_to "Show", project, class:"card-link btn btn-primary" %>
    </div>
  </div>
  <% end %>
  <% end %>
  </div>
  </div>
  <%= render 'projects/form' %>

  <% else %>
  <h1 class="h1">Basecamp</h1>
  
      
      <div class="button ">
        <%= link_to "Sign Up!", new_user_registration_path , class:"btn" %>

        <%= link_to "Login", new_user_session_path , class:"btn"%>
      </div>
  <% end %>

</div>


</body>

app/views/projects/_form.html.erb
<%= form_with(model: @project) do |form| %>
  <% if @project.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize( @project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Name:</label>
            <%= form.text_field :name, class:"form-control" %>
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Description:</label>
                <%= form.text_area :description, class:"form-control" %>
                  <%= form.number_field :user_id, id: :project_user_id, value: current_user.id, type: :hidden %>

          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
    <%= form.submit class:"btn btn-dark" %>

      </div>
    </div>
  </div>
</div>
  <div>
  </div>


<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <p>
    <strong>Name:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= project.user_id %>
  </p>

</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render "form", project: @project %>

<br>

<div>
  <%= link_to "Show this project", @project %> |
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/index.html.erb
<h1 class="h1-project">Projects</h1>

<%= stylesheet_link_tag "register" %>
<div id="projects">
  <% @projects.each do |project| %>
    <%= render project %>
    <p>
      <%= link_to "Show this project", project %>
    </p>
  <% end %>
</div>

<%= link_to "New project", new_project_path %>
<%= link_to "sign out", new_user_session_path %>

app/views/projects/new.html.erb
<h1>New project</h1>


<%= render "form", project: @project %>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form>
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Recipient:</label>
            <input type="text" class="form-control" id="recipient-name">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Message:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Send message</button>
      </div>
    </div>
  </div>
</div>


<br>

<div>
  <%= link_to "Back to projects", projects_path %>
</div>

app/views/projects/show.html.erb
<%= render 'form' %>

<div>
  <%= button_to "Destroy this project", @project, method: :delete, style: "float: right;", class: "btn btn-danger" %>
  <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin-right: 10px;">Edit Project</button>
  <h1 align="center"><%= @project.name %></h1>



</div>